version: 2.1

jobs:
  test:
    docker:
      - image: circleci/golang:1.13
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/nikmmd/optionspy-go
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: go mod download
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run: go test
